name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1,7,14 * * *'
permissions:
  contents: write
  actions: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install requests
    - name: Run update
      env:
        DINGDING_ACCESS_TOKEN: ${{ secrets.DINGDING_ACCESS_TOKEN }}
        DINGDING_SECRET: ${{ secrets.DINGDING_SECRET }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python run.py 2>&1 | tee /tmp/run_output.log
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto update: $(date +%Y-%m-%d\ %H:%M:%S)"
        git push